In [6]:
import numpy as np
import matplotlib.pyplot as plt

Parameters
lowint or array-like of ints
Lowest (signed) integers to be drawn from the distribution (unless high=None, in which case this parameter is 0 and this value is used for high).

highint or array-like of ints, optional
If provided, one above the largest (signed) integer to be drawn from the distribution (see above for behavior if high=None). If array-like, must contain integer values

sizeint or tuple of ints, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

dtypedtype, optional
Desired dtype of the result. Byteorder must be native. The default value is np.int64.

endpointbool, optional
If true, sample from the interval [low, high] instead of the default [low, high) Defaults to False

Returns
outint or ndarray of ints
size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.

Notes

When using broadcasting with uint64 dtypes, the maximum value (2**64) cannot be represented as a standard integer type. The high array (or low if high is None) must have object dtype, e.g., array([2**64]).

In [ ]:
random.Generator.integers(low, high=None, size=None, dtype=np.int64, endpoint=False)

This function generates random integers from `low` up to but not including `high` (unless `endpoint` is set to `True`). It will return integers from a discrete uniform distribution (also known as the "equally likely outcomes" distribution [https://mathworld.wolfram.com/DiscreteUniformDistribution.html]) of the `dtype` given (the default `dtype` is `np.int64`). 

Parameters:
- Low:

In [15]:
rng = np.random.default_rng()

In [7]:
rng = np.random.default_rng()
rng.integers(2, size=10)

array([1, 1, 1, 0, 1, 0, 1, 0, 0, 0], dtype=int64)

In [ ]:
rng.integers(1, size=10)

From: https://numpy.org/doc/stable/reference/random/generator.html

The function numpy.random.default_rng will instantiate a Generator with numpy’s default BitGenerator.

In [16]:
rng.integers(1, 3, 10, np.int64, True)

array([3, 3, 3, 1, 1, 2, 1, 3, 1, 1], dtype=int64)

In [17]:
rng.integers(1, 3, 10, np.int64, False)

array([2, 1, 1, 1, 1, 2, 2, 2, 1, 1], dtype=int64)

In [21]:
x = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0])

In [22]:
rng.random(6, out=x)

array([0.46581018, 0.26270611, 0.98002959, 0.47894245, 0.61501945,
       0.97052113])

In [85]:
rng.choice((1, 5, 3), 10, p=[.8, .15, .05])

array([1, 5, 1, 1, 1, 1, 1, 1, 1, 3])

`replace` means it won't repeat

In [188]:
rng.choice(5, 3, replace=False)

array([2, 4, 1], dtype=int64)

In [146]:
rng.choice(5, 3, replace=True)

array([1, 4, 4], dtype=int64)

In [147]:
mat = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

rng.choice(mat, 3, axis=0)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [148]:
rng.choice(mat, 3, axis=1)

array([[ 1,  2,  1],
       [ 5,  6,  5],
       [ 9, 10,  9]])

In [149]:
rng.bytes(10)

b'\x89~Dt\xaf1#x;C'